### ISSUE TITLE
Can you help me out

### ISSUE THREAD

**Issue by philly88r** [adamlui/chatgpt-infinity#16]
I use your infinity chatgpt toggle not the extension, I am sure I am not using this for what it was intended for.  I have made a new gpt and it works well with this infinity chatgpt.  The only issue I run into from time to time is how it says DO IT AGAIN is there anyway I can get a version that says continue.  An extra bonus would be if when you hit the toggle it didnt start a new chat, but thats not that big of a deal.  The main thing is the DO IT AGAIN.  even though i prompt it that do it again means to continue it still struggles sometimes.

**Comment by adamlui** [comment]
Hey @philly88r thank you for using my app! What happens sometimes in response to "do it again"? Maybe I can revise it to something more specific than "continue." Also if the toggle doesn't activate it, what are you thinking of adding? A button to start if toggle is on, and button disappears if toggle is off?

**Comment by philly88r** [comment]
@philly88r <https://github.com/philly88r> thank you for using my app! What
happens sometimes in response to "do it again"? Maybe I can revise it to
something more specific than "continue." Also if the toggle doesn't
activate it, what are you thinking of adding? A button to start if toggle
is on, and button disappears if toggle is off?

—

What happens sometimes in response to "do it again"? --- it actually
repeats or gives a different version of what it just did.  I realize that's
what it's supposed to do.  What I am using it for i want it to continue
with my long list of prompts. Most the time it works ok.  But sometimes it
just won't listen.  Replying with Continue would be amazing.


Also if the toggle doesn't activate it, what are you thinking of adding?
------the toggle does activate it but it takes it out of my conversation
and starts a whole new conversation.  Not a big deal because I can just go
back and click.

Another amazing feature would be ---- when I click on another page in my
browser the toggle automatically cuts off.  If there was any way to keep it
on even if you were not on the page.

**Comment by adamlui** [comment]
Can you share your gpt so I understand your use case more, also if you know JavaScript I could guide you to make a custom userscript for your purpose bu using chatgpt.js

**Comment by philly88r** [comment]
I am a marketing guy I do not know JavaScript.  I will share the gpt but I
think explaining it would be better.  I own a SEO agency.  In order to
write a blog that actually ranks on chat gpt you have to give several
prompts.  For instance it will write the title and outline then I have
stop.  Then it will write the first section and stop.  Then i have it add
tables and interlinks and so on.  There can be up to 10 sections.  If you
have to sit there and just say continue what's the purpose.  Your app let's
me walk away from it and do other things.  When it's completed these blogs
are top quality and normally rank fast.  But having to sit there and watch
it and hit continue makes the process aggravating.
I know there are other auto blogging services which I have tried, but none
produce quality like this.
When your app says do it again sometimes it just repeats the same section.
Let me know if that makes sense.

**Comment by adamlui** [comment]
Wow @philly88r I am quite intrigued by your technique, can you email me at adamlui@pm.me so you can share a blog I can read in private, then we can discuss a custom solution to your problem (either for you only or I make a new app)

**Comment by philly88r** [comment]
sent
