### ISSUE TITLE
ChatGPT  Infinity Mode UI Bug/Error

### ISSUE THREAD

**Issue by Joker1718** [adamlui/chatgpt-infinity#17]
## For the newer theme of chat.open.ai, Infinite Mode doesn't appear and the userscript version is not working when enabled manually.

**Ex.1**

New UI of OpenAI chat.openai.com
![2023_11_18_0zq](https://github.com/adamlui/chatgpt-infinity/assets/82336164/1b1e6559-9be4-4c36-bd90-fa90f392c331)

Issue:
![2023_11_18_0zs](https://github.com/adamlui/chatgpt-infinity/assets/82336164/5a92ebc3-b9e1-4ea0-802c-e860aece875a)

**Ex.2**
Issue : "Doesn't work for new ui, tested it out several platforms like chrome, edge, firefox, opera"
![2023_11_18_0zy](https://github.com/adamlui/chatgpt-infinity/assets/82336164/b0a2f16d-b9a7-476f-b5b4-79bc689d71dd)

Thank you :D, I had great using this extension and the usercript version. It helped a lot for acquiring new informations.

**Comment by adamlui** [comment]
Hey thanks for using it @Joker1718, what is the browser the userscript doesn't work in? And the script version?

**Comment by Chipsum** [comment]
same here not working

**Comment by adamlui** [comment]
hey @Chipsum what is your browser and are you using the extension, if not waht is the userscript manager?

**Comment by Chipsum** [comment]
@adamlui Chrome latest version, using tampermonkey with https://greasyfork.org/en/scripts/465051-chatgpt-infinity

**Comment by Chipsum** [comment]
![image](https://github.com/adamlui/chatgpt-infinity/assets/37517008/8469981a-d2d9-4c2e-9b87-82cb5721e8a6)

**Comment by adamlui** [comment]
Are you on a mac? your icons look different than mine, maybe the OpenAI UI is different for macs so the selector I wrote only worked for Windows to insert the toggle (which is required to be in sidebar to work)

**Comment by Chipsum** [comment]
Windows 11

**Comment by adamlui** [comment]
@Chipsum can you go to tampermonkey editor (click tampermoonkey icon right of address bar, then ">" next to ChatGPT Infinity, then Edit Script)  and change line 345 to

```js
    await chatgpt.history.isLoaded() ; insertToggle()
```

then press Ctrl + S and refresh chatgpt and see if it works?

**Comment by adamlui** [comment]
wait nvm the await statement is already in the function, idk how to fix it cuz i don't have windows 11 :(

**Comment by adamlui** [comment]
Can you try maybe the chrome extension might work? https://chrome.chatgptinfinity.com

**Comment by Chipsum** [comment]
with the extension, When I toggle infinity mode , it seems to switch, but when I open the extension again I find the switch off
and that's what it gives
![image](https://github.com/adamlui/chatgpt-infinity/assets/37517008/bc4b0721-9473-4953-9cef-a508b06499f5)

**Comment by Chipsum** [comment]
Dunno if that helps with targeting the correct node
![image](https://github.com/adamlui/chatgpt-infinity/assets/37517008/3a2a8b5f-f2ed-4da7-ae01-5fe00409c475)

**Comment by adamlui** [comment]
Can you expand the <a> ? (idk why your button says 'New chat' but that's the reason it's failing)

**Comment by adamlui** [comment]
(for me and others it says 'Clear chat' in prrivate mode or 'ChatGPT' in public mode)

**Comment by adamlui** [comment]
Sorry for some reason my message didn't show up , i meant expand the < a >

**Comment by Chipsum** [comment]
For the clear chat, it's when I press on my name in the bottom (I made it black for privacy)
![image](https://github.com/adamlui/chatgpt-infinity/assets/37517008/886b81ac-0f37-4964-b051-28a86b3bebb3)

and for the expanded a, this is the whole div that holds the upper portion (New Chat)
`<div class="pt-3.5"><div class="pb-0.5 last:pb-0" tabindex="0"><a class="group flex h-10 items-center gap-2 rounded-lg px-2 font-medium hover:bg-token-surface-primary" href="/"><div class="h-7 w-7 flex-shrink-0"><div class="gizmo-shadow-stroke relative flex h-full items-center justify-center rounded-full bg-white text-black"><svg width="41" height="41" viewBox="0 0 41 41" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-2/3 w-2/3" role="img"><text x="-9999" y="-9999">ChatGPT</text><path d="M37.5324 16.8707C37.9808 15.5241 38.1363 14.0974 37.9886 12.6859C37.8409 11.2744 37.3934 9.91076 36.676 8.68622C35.6126 6.83404 33.9882 5.3676 32.0373 4.4985C30.0864 3.62941 27.9098 3.40259 25.8215 3.85078C24.8796 2.7893 23.7219 1.94125 22.4257 1.36341C21.1295 0.785575 19.7249 0.491269 18.3058 0.500197C16.1708 0.495044 14.0893 1.16803 12.3614 2.42214C10.6335 3.67624 9.34853 5.44666 8.6917 7.47815C7.30085 7.76286 5.98686 8.3414 4.8377 9.17505C3.68854 10.0087 2.73073 11.0782 2.02839 12.312C0.956464 14.1591 0.498905 16.2988 0.721698 18.4228C0.944492 20.5467 1.83612 22.5449 3.268 24.1293C2.81966 25.4759 2.66413 26.9026 2.81182 28.3141C2.95951 29.7256 3.40701 31.0892 4.12437 32.3138C5.18791 34.1659 6.8123 35.6322 8.76321 36.5013C10.7141 37.3704 12.8907 37.5973 14.9789 37.1492C15.9208 38.2107 17.0786 39.0587 18.3747 39.6366C19.6709 40.2144 21.0755 40.5087 22.4946 40.4998C24.6307 40.5054 26.7133 39.8321 28.4418 38.5772C30.1704 37.3223 31.4556 35.5506 32.1119 33.5179C33.5027 33.2332 34.8167 32.6547 35.9659 31.821C37.115 30.9874 38.0728 29.9178 38.7752 28.684C39.8458 26.8371 40.3023 24.6979 40.0789 22.5748C39.8556 20.4517 38.9639 18.4544 37.5324 16.8707ZM22.4978 37.8849C20.7443 37.8874 19.0459 37.2733 17.6994 36.1501C17.7601 36.117 17.8666 36.0586 17.936 36.0161L25.9004 31.4156C26.1003 31.3019 26.2663 31.137 26.3813 30.9378C26.4964 30.7386 26.5563 30.5124 26.5549 30.2825V19.0542L29.9213 20.998C29.9389 21.0068 29.9541 21.0198 29.9656 21.0359C29.977 21.052 29.9842 21.0707 29.9867 21.0902V30.3889C29.9842 32.375 29.1946 34.2791 27.7909 35.6841C26.3872 37.0892 24.4838 37.8806 22.4978 37.8849ZM6.39227 31.0064C5.51397 29.4888 5.19742 27.7107 5.49804 25.9832C5.55718 26.0187 5.66048 26.0818 5.73461 26.1244L13.699 30.7248C13.8975 30.8408 14.1233 30.902 14.3532 30.902C14.583 30.902 14.8088 30.8408 15.0073 30.7248L24.731 25.1103V28.9979C24.7321 29.0177 24.7283 29.0376 24.7199 29.0556C24.7115 29.0736 24.6988 29.0893 24.6829 29.1012L16.6317 33.7497C14.9096 34.7416 12.8643 35.0097 10.9447 34.4954C9.02506 33.9811 7.38785 32.7263 6.39227 31.0064ZM4.29707 13.6194C5.17156 12.0998 6.55279 10.9364 8.19885 10.3327C8.19885 10.4013 8.19491 10.5228 8.19491 10.6071V19.808C8.19351 20.0378 8.25334 20.2638 8.36823 20.4629C8.48312 20.6619 8.64893 20.8267 8.84863 20.9404L18.5723 26.5542L15.206 28.4979C15.1894 28.5089 15.1703 28.5155 15.1505 28.5173C15.1307 28.5191 15.1107 28.516 15.0924 28.5082L7.04046 23.8557C5.32135 22.8601 4.06716 21.2235 3.55289 19.3046C3.03862 17.3858 3.30624 15.3413 4.29707 13.6194ZM31.955 20.0556L22.2312 14.4411L25.5976 12.4981C25.6142 12.4872 25.6333 12.4805 25.6531 12.4787C25.6729 12.4769 25.6928 12.4801 25.7111 12.4879L33.7631 17.1364C34.9967 17.849 36.0017 18.8982 36.6606 20.1613C37.3194 21.4244 37.6047 22.849 37.4832 24.2684C37.3617 25.6878 36.8382 27.0432 35.9743 28.1759C35.1103 29.3086 33.9415 30.1717 32.6047 30.6641C32.6047 30.5947 32.6047 30.4733 32.6047 30.3889V21.188C32.6066 20.9586 32.5474 20.7328 32.4332 20.5338C32.319 20.3348 32.154 20.1698 31.955 20.0556ZM35.3055 15.0128C35.2464 14.9765 35.1431 14.9142 35.069 14.8717L27.1045 10.2712C26.906 10.1554 26.6803 10.0943 26.4504 10.0943C26.2206 10.0943 25.9948 10.1554 25.7963 10.2712L16.0726 15.8858V11.9982C16.0715 11.9783 16.0753 11.9585 16.0837 11.9405C16.0921 11.9225 16.1048 11.9068 16.1207 11.8949L24.1719 7.25025C25.4053 6.53903 26.8158 6.19376 28.2383 6.25482C29.6608 6.31589 31.0364 6.78077 32.2044 7.59508C33.3723 8.40939 34.2842 9.53945 34.8334 10.8531C35.3826 12.1667 35.5464 13.6095 35.3055 15.0128ZM14.2424 21.9419L10.8752 19.9981C10.8576 19.9893 10.8423 19.9763 10.8309 19.9602C10.8195 19.9441 10.8122 19.9254 10.8098 19.9058V10.6071C10.8107 9.18295 11.2173 7.78848 11.9819 6.58696C12.7466 5.38544 13.8377 4.42659 15.1275 3.82264C16.4173 3.21869 17.8524 2.99464 19.2649 3.1767C20.6775 3.35876 22.0089 3.93941 23.1034 4.85067C23.0427 4.88379 22.937 4.94215 22.8668 4.98473L14.9024 9.58517C14.7025 9.69878 14.5366 9.86356 14.4215 10.0626C14.3065 10.2616 14.2466 10.4877 14.2479 10.7175L14.2424 21.9419ZM16.071 17.9991L20.4018 15.4978L24.7325 17.9975V22.9985L20.4018 25.4983L16.071 22.9985V17.9991Z" fill="currentColor" style=""></path></svg></div></div><div class="grow overflow-hidden text-ellipsis whitespace-nowrap text-sm text-token-text-primary">New chat</div><div class="flex gap-3" style=""><span class="flex items-center" data-state="closed" style=""><button class="text-token-text-primary" style=""><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="icon-md" style=""><path fill-rule="evenodd" clip-rule="evenodd" d="M16.7929 2.79289C18.0118 1.57394 19.9882 1.57394 21.2071 2.79289C22.4261 4.01184 22.4261 5.98815 21.2071 7.20711L12.7071 15.7071C12.5196 15.8946 12.2652 16 12 16H9C8.44772 16 8 15.5523 8 15V12C8 11.7348 8.10536 11.4804 8.29289 11.2929L16.7929 2.79289ZM19.7929 4.20711C19.355 3.7692 18.645 3.7692 18.2071 4.2071L10 12.4142V14H11.5858L19.7929 5.79289C20.2308 5.35499 20.2308 4.64501 19.7929 4.20711ZM6 5C5.44772 5 5 5.44771 5 6V18C5 18.5523 5.44772 19 6 19H18C18.5523 19 19 18.5523 19 18V14C19 13.4477 19.4477 13 20 13C20.5523 13 21 13.4477 21 14V18C21 19.6569 19.6569 21 18 21H6C4.34315 21 3 19.6569 3 18V6C3 4.34314 4.34315 3 6 3H10C10.5523 3 11 3.44771 11 4C11 4.55228 10.5523 5 10 5H6Z" fill="currentColor"></path></svg></button></span></div></a></div></div>`

**Comment by adamlui** [comment]
I'm not sure this wil work because your paste is really long and hard to read, but around line 607 the lline beginning `firstButton = `, can you replace it and the next line with

```js
              firstButton = [...navButtons].find(button => {
                  const re_firstButton = chatgpt.history.isOff() ? /ChatGPTClear/ : /ChatGPTChatGPT|New chat/
                  return re_firstButton.test(button.textContent)
              })
```

**Comment by Chipsum** [comment]
Now it's working:
![image](https://github.com/adamlui/chatgpt-infinity/assets/37517008/36400335-44e2-4950-af3e-d9a1674a97a2)

**Comment by adamlui** [comment]
But the button label didn't show up :(

**Comment by Chipsum** [comment]
I copied the whole page's source, beautified 
https://paste.fo/199f263cda26

**Comment by adamlui** [comment]
@Chipsum can you refresh, when does the upgrade button appear relative to new chat button, chat history and your username

**Comment by Chipsum** [comment]
![image](https://github.com/adamlui/chatgpt-infinity/assets/37517008/ab9819ad-ce21-4b31-8dd9-3f391c4abdf9)
The upgrade button and username button appears but like any other elements in the page, with page load.
chat history is a popup from when I click on username and then settings:
![image](https://github.com/adamlui/chatgpt-infinity/assets/37517008/3d793d44-c7e9-4fb2-80fc-d76f52a0d853)

![image](https://github.com/adamlui/chatgpt-infinity/assets/37517008/c254513a-728f-4d1c-8c97-9a66d8f2825a)

**Comment by Chipsum** [comment]
This is the html for the two of the buttons:
https://paste.fo/804ffa1093cf

& 

this is for the clear history popup
https://paste.fo/c9f0fea4b0eb

**Comment by adamlui** [comment]
@Chipsum can you try replacing the userscript with this oine and see how it looks https://paste.fo/8db8f3979ca0

**Comment by Chipsum** [comment]
@adamlui 
![image](https://github.com/adamlui/chatgpt-infinity/assets/37517008/a0b5fa21-0c5d-493e-ada4-221502560834)

**Comment by Chipsum** [comment]
https://github.com/adamlui/chatgpt-infinity/assets/37517008/896ea9da-f330-4282-80b9-c96af0978635

**Comment by adamlui** [comment]
Sorry this is too hard to do without being on the page and I am getting a big headache from it

**Comment by Chipsum** [comment]
https://github.com/adamlui/chatgpt-infinity/assets/37517008/fbc39f79-7b73-4fc2-a17c-69c55e120e44

**Comment by Chipsum** [comment]
> Sorry this is too hard to do without being on the page and I am getting a big headache from it

Relax and take it slow, work whenever you want

**Comment by adamlui** [comment]
... but the change I made that if works will fix it, is in ~line 633's `updateToggleHTML()`

```js
        // Create/stylize/fill label
        const toggleLabel = document.querySelector('#infToggleLabel') || document.createElement('label')
        toggleLabel.id = 'infToggleLabel'
        chatgpt.history.isLoaded().then(() => {
            const chatHistoryNav = document.querySelector('nav[aria-label="Chat history"]') || {},
                  navButtons = chatHistoryNav.querySelectorAll('a'),
                  upgradeBtn = [...navButtons].find(button => button.textContent.includes('Upgrade'))
            toggleLabel.style.margin = upgradeBtn ? '-2px 0 0 -24px' : '0 0 0 -41px' // fine-tune text pos
            toggleLabel.style.cursor = 'pointer' // add finger cursor on hover
            toggleLabel.innerText = ( messages.menuLabel_infinityMode || 'Infinity Mode' ) + ' '
                                  + ( toggleInput.checked ? ( messages.state_enabled  || 'enabled' )
                                                          : ( messages.state_disabled || 'disabled' ))
            if (upgradeBtn) { toggleLabel.color = 'var(--text-primary)' ; toggleLabel.fontSize = '.875rem' }
        })
```

For some reason it is not detectingn the upgradeBtn, even though it is detected on the version you sent me

**Comment by adamlui** [comment]
Your interface is different because not Pro user I believe. My pro membership will expire tomrrow so I can see it like yours then

**Comment by Joker1718** [comment]
Damn, i never thought it would get a lot of comments for a few months. Today 17 Jan 2024 the issue  will be closed.



> @Joker1718 hey did the latest versions ever fix it for you?

@adamlui Yes, It was fixed on the month of December. Much Appreciated...
