### ISSUE TITLE
Is this broken?

### ISSUE THREAD

**Issue by Nisthar** [adamlui/chatgpt-infinity#2]
I am not sure what it does. I think you should include a video demo of it.

I installed the extension, it opened chatgpt right after install and created a bunch of new chats automatically and sending messages automatically.

**Comment by adamlui** [comment]
@Nisthar hey it is broken if it began sending messages without you activating the switch. Did you activate the switch, then it sent messages? If so, it is working as intended, which is ask ChatGPT to generate answers to random questions automatically (you can also set the topic to be less random by using the extension menu::

![image](https://github.com/adamlui/chatgpt-infinity/assets/10906554/83dbc687-21ed-4b4d-8088-88c11dc70190)

For easier access to the menu, you can pin the extension to the toolbar:

![chrome-extension-pin-instructions](https://github.com/adamlui/chatgpt-infinity/assets/10906554/c879fe33-ec96-4bd9-889d-72de5c391ade)

**Comment by Laimen-hub** [comment]
я не совсем понимаю как это работает. Я скачал расширение к браузеру хром и всё, го у меня нет бесконечного режима можете подсказать что ещё мне надо скачать или сделать что бы программа работала

**Comment by adamlui** [comment]
@Laimen-hub вот видео (должно автоматически запускаться с 0:49), показывающее, как это работает: https://youtu.be/yG8DtsEo0PM?si=XxOOpaSq-biHZGJ8&t=49

Этот переключатель не появляется на боковой панели после его установки?

![image](https://github.com/adamlui/chatgpt-infinity/assets/10906554/973014ed-b86b-498b-8f11-c28353fff632)

**Comment by Laimen-hub** [comment]
честно сказать у меня даже чатGPT не работает я нажимаю кнопку начать, он загружает но после ничего не происходит

**Comment by adamlui** [comment]
@Laimen-hub Вам обычно помогает посещение https://chat.openai.com?

**Comment by Laimen-hub** [comment]
![Снимок](https://github.com/adamlui/chatgpt-infinity/assets/148681021/9925accb-fed3-4d66-a230-60cffc8a1d2b)

он пишет невозможно загрузить сайт, но зразу говорю впн у меня нет

**Comment by adamlui** [comment]
@Laimen-hub Здесь я поделюсь с вами секретным клоном https://chat.aivvm.com/

**Comment by Laimen-hub** [comment]
у него почему то либо на первом слове обрезается либо ничего не видно

**Comment by adamlui** [comment]
@Laimen-hub Вот еще альтернативы:

https://sdk.vercel.ai/
https://poe.com

**Comment by Laimen-hub** [comment]
а в poe как сделать бесконечный gpt

**Comment by adamlui** [comment]
@Laimen-hub Я не писал расширение для Poe, но, по крайней мере, теперь вы можете общаться в ChatGPT.

**Comment by Laimen-hub** [comment]
прикол в том что на sdk.vercel такая же проблема что 1 слово обрезается и дальше не пишет а poe я не могу ни на одном боте ничего написать ведь он пишет что бот не доступен в вашем регионе

**Comment by adamlui** [comment]
@Laimen-hub Вам стоит попробовать VPN на Poe

**Comment by adamlui** [comment]
@Laimen-hub Также попробуйте [claude.ai](https://claude.ai) (не ChatGPT, но в некотором смысле более мощный) с включением и выключением VPN.
